### PR TITLE
Tumble support

### PR DESCRIPTION
**Pull request by evanmiller**
This is a follow-up to https://github.com/pdewacht/brlaser/pull/124. Several users reported that that PR didn't work, so I've modified the logic to use PCL commands instead of PJL. Tested locally on an HL-2300D printer.

### CODE REVIEW

**Comment by Isaacych** [comment]
@evanmiller 

In job.cc, I found that "page_params_.tumble" is always False no matter what print option are selected, such that the duplex long edge flipping does not work. I modified that block code as the following. 

`if (page_params_.duplex) {`
`    if (page_params_.tumble) {`
`	    fputs("\033&l1S", out_);`
`    } else {`
`	    fputs("\033&l2S", out_);`
`    } `
`  } else {`
`    fputs("\033&l0S", out_);`
`  }`

The duplex short edge flipping does not work now. Seems to relate to some other issues. But at least the duplex no tumble option works for my HL-2300D printer. Thanks for your update.

**Comment by evanmiller** [comment]
@Isaacych Did you apply the suggested change in `main.cc` as well? That should ensure that `tumble` is set appropriately.

**Comment by Isaacych** [comment]
> @Isaacych Did you apply the suggested change in `main.cc` as well? That should ensure that `tumble` is set appropriately.

I did. I edited the code based on the version you have. Somehow the `tumble ` is not responding.

**Comment by QORTEC** [comment]
Thanks moving over to [Owl-Maintain/brlaser](https://github.com/Owl-Maintain/brlaser).

**Pull request merged**
